server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  task:
    scheduling:
      pool:
        size: 10
      thread-name-prefix: scheduled-task-
      shutdown:
        await-termination: true
        await-termination-period: 60s

upload:
  path: /data/uploads/prod 